config/routes.rb
Rails.application.routes.draw do
  get 'movie/index'
  get 'show/:id', :to => "movie#show", :as => :show

  post 'create', :to => "movie#create"
  get 'new', :to => "movie#new", :as => :new
  root "movie#index"
  # list methods
  get 'list', :to => "list#index", :as => :list_index
  get 'list/show/:id', :to => "list#show", :as => :list_show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6,maximum: 1000,
    too_long: "%{count} characters is the maximum allowed" }
    validates :movie_id, uniqueness: {scope: :list_id, message: "is already in the list"}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: %i[ show ]

  def index
    @list = List.all
  end

  def show

  end

  def edit
  end

  def update
  end

  def destroy
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  before_action :set_movie, only: %i[ show ]
  protect_from_forgery
  def index
    @movies = Movie.all
    l = @movies.count
    index = rand(0..l)
    @movie = @movies[index]
  end

  def show
  end

  def new
  end

  def create
    @list = List.create(name: params[:name])
    @list.save
  end
  private

  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FM</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
    <div class="logo"></div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a href="/list" class="">My List</a>
        <a href="/new" class="">New List</a>
          </div>
        </div>
    </div>
    <div class="main-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/list/destroy.html.erb
<h1>List#destroy</h1>
<p>Find me in app/views/list/destroy.html.erb</p>

app/views/list/edit.html.erb
<h1>List#edit</h1>
<p>Find me in app/views/list/edit.html.erb</p>

app/views/list/index.html.erb
<div class="container">
  <h1>Playlists</h1>
    <%@list.each do |l|  %>
    <div class="card-product">
    <%= image_tag("") %>
      <div class="card-product-infos">
        <h2><%= link_to l.name, list_show_path(l.id) %></h2>
      </div>
    </div>
    <% end %>
</div>

app/views/list/show.html.erb
<h1>List#show</h1>

app/views/list/update.html.erb
<h1>List#update</h1>
<p>Find me in app/views/list/update.html.erb</p>

app/views/movie/index.html.erb
<div class="home-banner-image">
      <%= image_tag(@movie.post_url, :class => "img-fluid") %>
      <div class="wrap">
        <div class="content">
          <h1><%= (@movie.title) %></h1>
          <p><%= (@movie.overview ) %></p>
          <p class="rating"><%= (@movie.rating) %></p>
        </div>
      </div>
  </div>
</div>

<div class="wrap-cards">
  <h1>Movies</h1>
  <div class="cards">
    <%@movies.each do |movie|  %>
      <div class="card">
          <%= image_tag(movie.post_url, :class => "card-img-top") %>
          <p class="title"><%= (movie.title) %></p>
          <p class="sub"><%= (movie.overview.slice(0, 25) + "...")  %></p>
          <div class="card-bottom">
            <%= link_to "Show details", show_path(movie.id) %>
            <p class="rating"><%= (movie.rating) %></p>
          </div>
      </div>
      <% end %>
  </div>
</div>

app/views/movie/new.html.erb
<div class="container">
  <h1>Create List</h1>
  <form action="/create" method="post">
  <div class="list">
    <div class=list-content>
      <label for="list-name">Image</label>
      <input type="file" name="image" >
    </div>
    <div class=list-content>
      <label for="list-name">Name</label>
      <input type="text" name="name" >
    </div>
  </div>
    <input type="submit" value="Create List">
  </form>
</div>

app/views/movie/show.html.erb
<div class="div">
  <div class="home-banner-image">
    <%= image_tag(@movie.post_url, :class => "img-fluid") %>
    <div class="wrap">
      <div class="content">
        <h1><%= (@movie.title) %></h1>
        <p><%= (@movie.overview ) %></p>
        <p class="rating"><%= (@movie.rating) %></p>
      </div>
    </div>
  </div>
    <div class="details">
      <h4><%= (@movie.title) %></h4>
      <p><%= (@movie.overview )  %></p>
      <p class="rating"><%= (@movie.rating) %></p>
      <button>Add to list</button>
      <button>Add Review</button>
      <%= link_to "Go back", movie_index_path %>
    </div>
</div>